-- =============================================================
-- Catálogo de ocupaciones para sistema agro (español / inglés)
-- Versión para PostgreSQL 12+ (UTF-8)
-- Uso: psql -U usuario -d base -f catalogo_ocupaciones_agro_postgres.sql
--
-- codigo_ciuo: referencia a la Clasificación Internacional Uniforme de
-- Ocupaciones CIUO-08 / ISCO-08 de la OIT (grupo unitario, 4 dígitos).
-- Sirve para reportes estadísticos; es NULL cuando no aplica.
-- =============================================================

SET client_encoding = 'UTF8';

BEGIN;

DROP VIEW  IF EXISTS v_ocupacion;
DROP TABLE IF EXISTS ocupacion;
DROP TABLE IF EXISTS categoria_ocupacion;

CREATE TABLE categoria_ocupacion (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo    VARCHAR(10)  NOT NULL UNIQUE,
    nombre_es VARCHAR(100) NOT NULL,
    nombre_en VARCHAR(100) NOT NULL,
    orden     SMALLINT     NOT NULL DEFAULT 0,
    activo    BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE ocupacion (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id  INTEGER      NOT NULL,
    codigo        VARCHAR(20)  NOT NULL UNIQUE,
    nombre_es     VARCHAR(120) NOT NULL,
    nombre_en     VARCHAR(120) NOT NULL,
    codigo_ciuo   CHAR(4),
    requiere_detalle BOOLEAN   NOT NULL DEFAULT FALSE,  -- TRUE = pedir texto libre (ej. "Otro")
    orden         SMALLINT     NOT NULL DEFAULT 0,
    activo        BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_ocupacion_categoria FOREIGN KEY (categoria_id)
        REFERENCES categoria_ocupacion(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX ix_ocupacion_categoria ON ocupacion(categoria_id);
CREATE INDEX ix_ocupacion_nombre_es ON ocupacion(nombre_es);
CREATE INDEX ix_ocupacion_nombre_en ON ocupacion(nombre_en);

COMMENT ON TABLE  categoria_ocupacion IS 'Agrupación de ocupaciones del sector agro';
COMMENT ON TABLE  ocupacion IS 'Ocupaciones que puede seleccionar un usuario del sistema agro';
COMMENT ON COLUMN ocupacion.codigo_ciuo IS 'Grupo unitario CIUO-08 / ISCO-08 (OIT)';
COMMENT ON COLUMN ocupacion.requiere_detalle IS 'Si es TRUE, la interfaz debe pedir una descripción libre';

-- ---------------- CATEGORÍAS ----------------
INSERT INTO categoria_ocupacion (id, codigo, nombre_es, nombre_en, orden) VALUES
  (1,  'AGR', 'Producción agrícola',               'Crop production',                     1),
  (2,  'PEC', 'Producción pecuaria',               'Livestock production',                2),
  (3,  'ACU', 'Acuicultura y pesca',               'Aquaculture and fishing',             3),
  (4,  'FOR', 'Forestal',                          'Forestry',                            4),
  (5,  'GES', 'Gestión y administración de fincas','Farm management and administration',  5),
  (6,  'TEC', 'Profesionales y técnicos agro',     'Agricultural professionals and technicians', 6),
  (7,  'SAN', 'Sanidad animal y vegetal',          'Animal and plant health',             7),
  (8,  'MAQ', 'Maquinaria y operaciones de campo', 'Machinery and field operations',      8),
  (9,  'IND', 'Agroindustria y procesamiento',     'Agribusiness and food processing',    9),
  (10, 'COM', 'Comercio, logística y distribución','Trade, logistics and distribution',  10),
  (11, 'FIN', 'Finanzas, seguros y servicios',     'Finance, insurance and services',    11),
  (12, 'INS', 'Gobierno, gremios y educación',     'Government, associations and education', 12),
  (13, 'TIC', 'Tecnología',                        'Technology',                         13),
  (14, 'OTR', 'Otros',                             'Other',                              14);

-- ---------------- OCUPACIONES ----------------
INSERT INTO ocupacion (categoria_id, codigo, nombre_es, nombre_en, codigo_ciuo, orden) VALUES
  -- Producción agrícola
  (1, 'AGR-001', 'Productor agrícola',                        'Crop farmer',                          '6111', 1),
  (1, 'AGR-002', 'Productor de granos (arroz, maíz, frijol)', 'Grain grower (rice, corn, beans)',     '6111', 2),
  (1, 'AGR-003', 'Productor de hortalizas',                   'Vegetable grower',                     '6111', 3),
  (1, 'AGR-004', 'Productor de frutas',                       'Fruit grower',                         '6112', 4),
  (1, 'AGR-005', 'Productor de café',                         'Coffee grower',                        '6112', 5),
  (1, 'AGR-006', 'Productor de cacao',                        'Cocoa grower',                         '6112', 6),
  (1, 'AGR-007', 'Productor de caña de azúcar',               'Sugarcane grower',                     '6111', 7),
  (1, 'AGR-008', 'Productor de plátano y banano',             'Plantain and banana grower',           '6112', 8),
  (1, 'AGR-009', 'Productor de raíces y tubérculos',          'Root and tuber crop grower',           '6111', 9),
  (1, 'AGR-010', 'Floricultor',                               'Flower grower',                        '6113', 10),
  (1, 'AGR-011', 'Viverista',                                 'Nursery grower',                       '6113', 11),
  (1, 'AGR-012', 'Productor de cultivos mixtos',              'Mixed crop grower',                    '6114', 12),
  (1, 'AGR-013', 'Productor orgánico',                        'Organic farmer',                       '6114', 13),
  (1, 'AGR-014', 'Productor de cultivos bajo invernadero',    'Greenhouse grower',                    '6113', 14),
  (1, 'AGR-015', 'Productor de subsistencia',                 'Subsistence farmer',                   '6310', 15),
  (1, 'AGR-016', 'Jornalero agrícola / peón de cultivos',     'Crop farm labourer',                   '9211', 16),
  (1, 'AGR-017', 'Jardinero / trabajador de horticultura',    'Garden and horticultural labourer',    '9214', 17),
  -- Producción pecuaria
  (2, 'PEC-001', 'Ganadero (bovinos de carne)',               'Beef cattle rancher',                  '6121', 1),
  (2, 'PEC-002', 'Productor de leche',                        'Dairy farmer',                         '6121', 2),
  (2, 'PEC-003', 'Porcicultor',                               'Pig farmer',                           '6121', 3),
  (2, 'PEC-004', 'Avicultor',                                 'Poultry farmer',                       '6122', 4),
  (2, 'PEC-005', 'Apicultor',                                 'Beekeeper',                            '6123', 5),
  (2, 'PEC-006', 'Productor de ovinos y caprinos',            'Sheep and goat farmer',                '6121', 6),
  (2, 'PEC-007', 'Productor equino',                          'Horse breeder',                        '6121', 7),
  (2, 'PEC-008', 'Productor de especies menores',             'Small livestock producer',             '6129', 8),
  (2, 'PEC-009', 'Productor agropecuario mixto',              'Mixed crop and livestock farmer',      '6130', 9),
  (2, 'PEC-010', 'Vaquero / peón ganadero',                   'Cowhand / livestock farm labourer',    '9212', 10),
  (2, 'PEC-011', 'Ordeñador',                                 'Milker',                               '9212', 11),
  (2, 'PEC-012', 'Jornalero agropecuario',                    'Mixed crop and livestock labourer',    '9213', 12),
  (2, 'PEC-013', 'Técnico en inseminación artificial',        'Artificial insemination technician',   '3240', 13),
  (2, 'PEC-014', 'Herrador',                                  'Farrier',                              '7221', 14),
  -- Acuicultura y pesca
  (3, 'ACU-001', 'Acuicultor',                                'Aquaculture farmer',                   '6221', 1),
  (3, 'ACU-002', 'Camaronicultor',                            'Shrimp farmer',                        '6221', 2),
  (3, 'ACU-003', 'Productor de tilapia y peces',              'Tilapia and fish farmer',              '6221', 3),
  (3, 'ACU-004', 'Pescador artesanal',                        'Artisanal fisher',                     '6222', 4),
  (3, 'ACU-005', 'Pescador de altura',                        'Deep-sea fisher',                      '6223', 5),
  (3, 'ACU-006', 'Peón de acuicultura y pesca',               'Fishery and aquaculture labourer',     '9216', 6),
  -- Forestal
  (4, 'FOR-001', 'Productor forestal / reforestador',         'Forestry producer / reforester',       '6210', 1),
  (4, 'FOR-002', 'Trabajador forestal',                       'Forestry worker',                      '6210', 2),
  (4, 'FOR-003', 'Peón forestal',                             'Forestry labourer',                    '9215', 3),
  (4, 'FOR-004', 'Técnico forestal',                          'Forestry technician',                  '3143', 4),
  (4, 'FOR-005', 'Ingeniero forestal',                        'Forestry engineer',                    '2132', 5),
  -- Gestión y administración de fincas
  (5, 'GES-001', 'Dueño de finca',                            'Farm owner',                           '1311', 1),
  (5, 'GES-002', 'Administrador de finca',                    'Farm manager',                         '1311', 2),
  (5, 'GES-003', 'Capataz / mayordomo',                       'Farm foreman',                         '6121', 3),
  (5, 'GES-004', 'Gerente de producción agrícola',            'Agricultural production manager',      '1311', 4),
  (5, 'GES-005', 'Gerente de acuicultura y pesca',            'Aquaculture and fisheries manager',    '1312', 5),
  (5, 'GES-006', 'Encargado de bodega / almacén',             'Warehouse keeper / stock clerk',       '4321', 6),
  (5, 'GES-007', 'Asistente administrativo agrícola',         'Agricultural administrative assistant','4110', 7),
  -- Profesionales y técnicos agro
  (6, 'TEC-001', 'Ingeniero agrónomo',                        'Agronomist',                           '2132', 1),
  (6, 'TEC-002', 'Zootecnista',                               'Animal scientist',                     '2132', 2),
  (6, 'TEC-003', 'Asesor / extensionista agrícola',           'Agricultural extension officer',       '2132', 3),
  (6, 'TEC-004', 'Técnico agropecuario',                      'Agricultural technician',              '3142', 4),
  (6, 'TEC-005', 'Ingeniero agrícola',                        'Agricultural engineer',                '2144', 5),
  (6, 'TEC-006', 'Especialista en riego y drenaje',           'Irrigation and drainage specialist',   '2142', 6),
  (6, 'TEC-007', 'Especialista en suelos',                    'Soil scientist',                       '2132', 7),
  (6, 'TEC-008', 'Biólogo / botánico',                        'Biologist / botanist',                 '2131', 8),
  (6, 'TEC-009', 'Técnico de laboratorio agrícola',           'Agricultural laboratory technician',   '3141', 9),
  (6, 'TEC-010', 'Especialista ambiental',                    'Environmental specialist',             '2133', 10),
  (6, 'TEC-011', 'Topógrafo',                                 'Surveyor',                             '2165', 11),
  (6, 'TEC-012', 'Investigador agrícola',                     'Agricultural researcher',              '2132', 12),
  -- Sanidad animal y vegetal
  (7, 'SAN-001', 'Médico veterinario',                        'Veterinarian',                         '2250', 1),
  (7, 'SAN-002', 'Técnico veterinario / asistente',           'Veterinary technician / assistant',    '3240', 2),
  (7, 'SAN-003', 'Fitopatólogo / fitosanitarista',            'Plant pathologist / plant health specialist', '2132', 3),
  (7, 'SAN-004', 'Inspector sanitario agropecuario',          'Agricultural health inspector',        '3257', 4),
  (7, 'SAN-005', 'Aplicador de agroquímicos',                 'Agrochemical applicator',              '9211', 5),
  (7, 'SAN-006', 'Cuidador de animales',                      'Animal care worker',                   '5164', 6),
  -- Maquinaria y operaciones de campo
  (8, 'MAQ-001', 'Operador de tractor y maquinaria agrícola', 'Tractor and farm machinery operator',  '8341', 1),
  (8, 'MAQ-002', 'Operador de cosechadora',                   'Combine harvester operator',           '8341', 2),
  (8, 'MAQ-003', 'Mecánico de maquinaria agrícola',           'Agricultural machinery mechanic',      '7233', 3),
  (8, 'MAQ-004', 'Piloto de fumigación aérea',                'Agricultural aircraft pilot',          '3153', 4),
  (8, 'MAQ-005', 'Operador de drones agrícolas',              'Agricultural drone operator',          '3153', 5),
  (8, 'MAQ-006', 'Instalador de sistemas de riego',           'Irrigation system installer',          '7126', 6),
  (8, 'MAQ-007', 'Contratista de servicios agrícolas',        'Agricultural services contractor',     NULL,   7),
  -- Agroindustria y procesamiento
  (9, 'IND-001', 'Procesador de alimentos',                   'Food processor',                       '7510', 1),
  (9, 'IND-002', 'Elaborador de productos lácteos',           'Dairy products maker',                 '7513', 2),
  (9, 'IND-003', 'Carnicero / procesador de carne',           'Butcher / meat processor',             '7511', 3),
  (9, 'IND-004', 'Catador / clasificador de productos',       'Product taster and grader',            '7515', 4),
  (9, 'IND-005', 'Operador de planta procesadora',            'Food processing plant operator',       '8160', 5),
  (9, 'IND-006', 'Operador de molino / beneficio',            'Mill operator',                        '8160', 6),
  (9, 'IND-007', 'Supervisor de planta agroindustrial',       'Agro-industrial plant supervisor',     '3122', 7),
  (9, 'IND-008', 'Ingeniero en alimentos',                    'Food engineer',                        '2145', 8),
  (9, 'IND-009', 'Especialista en calidad e inocuidad',       'Quality and food safety specialist',   '2263', 9),
  (9, 'IND-010', 'Empacador',                                 'Packer',                               '9321', 10),
  -- Comercio, logística y distribución
  (10, 'COM-001', 'Comerciante de productos agrícolas',       'Agricultural produce trader',          '3324', 1),
  (10, 'COM-002', 'Intermediario / acopiador',                'Produce broker / collector',           '3324', 2),
  (10, 'COM-003', 'Exportador / importador',                  'Exporter / importer',                  '3331', 3),
  (10, 'COM-004', 'Vendedor de insumos agropecuarios',        'Farm supplies salesperson',            '3322', 4),
  (10, 'COM-005', 'Dueño de agroveterinaria / agrotienda',    'Farm supply store owner',              '5221', 5),
  (10, 'COM-006', 'Vendedor de mercado / feria',              'Market vendor',                        '5211', 6),
  (10, 'COM-007', 'Comprador',                                'Buyer',                                '3323', 7),
  (10, 'COM-008', 'Transportista de carga',                   'Freight truck driver',                 '8332', 8),
  (10, 'COM-009', 'Coordinador de logística',                 'Logistics coordinator',                '4323', 9),
  (10, 'COM-010', 'Gerente de cadena de suministro',          'Supply chain manager',                 '1324', 10),
  (10, 'COM-011', 'Especialista en mercadeo agrícola',        'Agricultural marketing specialist',    '2431', 11),
  -- Finanzas, seguros y servicios
  (11, 'FIN-001', 'Oficial de crédito agropecuario',          'Agricultural loan officer',            '3312', 1),
  (11, 'FIN-002', 'Agente de seguros agrícolas',              'Agricultural insurance agent',         '3321', 2),
  (11, 'FIN-003', 'Contador',                                 'Accountant',                           '2411', 3),
  (11, 'FIN-004', 'Asesor financiero',                        'Financial advisor',                    '2412', 4),
  (11, 'FIN-005', 'Perito / tasador agropecuario',            'Agricultural appraiser',               '3315', 5),
  (11, 'FIN-006', 'Abogado agrario',                          'Agrarian lawyer',                      '2611', 6),
  (11, 'FIN-007', 'Consultor agropecuario',                   'Agricultural consultant',              '2132', 7),
  -- Gobierno, gremios y educación
  (12, 'INS-001', 'Funcionario público del sector agro',      'Agricultural government official',     '3359', 1),
  (12, 'INS-002', 'Miembro de cooperativa',                   'Cooperative member',                   NULL,   2),
  (12, 'INS-003', 'Directivo de gremio o asociación',         'Producer association leader',          '1114', 3),
  (12, 'INS-004', 'Docente universitario',                    'University lecturer',                  '2310', 4),
  (12, 'INS-005', 'Docente de formación técnica',             'Vocational education teacher',         '2320', 5),
  (12, 'INS-006', 'Estudiante de carrera agropecuaria',       'Agricultural sciences student',        NULL,   6),
  (12, 'INS-007', 'Representante de ONG / cooperación',       'NGO / development agency representative', '1114', 7),
  -- Tecnología
  (13, 'TIC-001', 'Desarrollador de software',                'Software developer',                   '2512', 1),
  (13, 'TIC-002', 'Analista de datos',                        'Data analyst',                         '2511', 2),
  (13, 'TIC-003', 'Especialista en agricultura de precisión', 'Precision agriculture specialist',     '2132', 3),
  (13, 'TIC-004', 'Especialista en SIG / teledetección',      'GIS / remote sensing specialist',      '2165', 4),
  -- Otros
  (14, 'OTR-001', 'Pensionado / jubilado',                    'Retiree',                              NULL,   1),
  (14, 'OTR-002', 'Ama / amo de casa',                        'Homemaker',                            NULL,   2),
  (14, 'OTR-003', 'Estudiante',                               'Student',                              NULL,   3),
  (14, 'OTR-004', 'Desempleado',                              'Unemployed',                           NULL,   4);

INSERT INTO ocupacion (categoria_id, codigo, nombre_es, nombre_en, codigo_ciuo, requiere_detalle, orden) VALUES
  (14, 'OTR-999', 'Otra ocupación (especifique)',             'Other occupation (please specify)',    NULL,   TRUE, 99);

-- Ajustar secuencias
SELECT setval(pg_get_serial_sequence('categoria_ocupacion','id'), (SELECT MAX(id) FROM categoria_ocupacion));
SELECT setval(pg_get_serial_sequence('ocupacion','id'),           (SELECT MAX(id) FROM ocupacion));

-- ---------------- VISTA PARA LA APP ----------------
-- Devuelve la lista lista para un selector agrupado, en ambos idiomas.
CREATE VIEW v_ocupacion AS
SELECT o.id,
       o.codigo,
       o.nombre_es,
       o.nombre_en,
       o.codigo_ciuo,
       o.requiere_detalle,
       c.codigo    AS categoria_codigo,
       c.nombre_es AS categoria_es,
       c.nombre_en AS categoria_en,
       c.orden     AS categoria_orden,
       o.orden
FROM ocupacion o
JOIN categoria_ocupacion c ON c.id = o.categoria_id
WHERE o.activo AND c.activo;

COMMIT;
